Allow cargo-dylint to besuccesfully run on Windows.
trailofbits/dylint pull request #43
Opened 2021-07-28 23:41 UTC by MinerSebas

This PR fixes `cargo-dylint` to run successfully on Windows.

Changes:
 - Usage of [`dirs::home_dir`](https://docs.rs/dirs/3.0.2/dirs/fn.home_dir.html) from the [dirs](https://crates.io/crates/dirs) crate to get the HOME directory.
 - Account for the fact that on windows the dylint driver is created with a file extension.
 - To successfully determine the driver Version, copies of the toolchain dll's were placed next to the driver.

`dylint-link` does not yet work windows. The correct library names for the examples are:
```
allow_clippy@nightly-2021-02-11-x86_64-pc-windows-msvc.dll
clippy@nightly-2021-04-08-x86_64-pc-windows-msvc.dll
env_literal@nightly-2021-04-08-x86_64-pc-windows-msvc.dll
path_separator_in_string_literal@nightly-2021-04-08-x86_64-pc-windows-msvc.dll
path_separator_in_string_literal@nightly-2021-04-08-x86_64-pc-windows-msvc.dll
```

2021-07-28 23:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/trailofbits/dylint?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/trailofbits/dylint?pullRequest=43) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/trailofbits/dylint?pullRequest=43) it.</sub>

2021-07-29 00:12 UTC, smoelius commented
Hey, @MinerSebas. This looks really good!

It looks like you're still pushing changes, though? Could you please ping me once you're happy with it?

2021-07-29 00:40 UTC, MinerSebas commented
@smoelius I am finished with my changes.
I had just a small churn due to the `unused-imports` lint, as the `read_dir` function was not necessary on Linux.

2021-07-29 01:10 UTC, smoelius commented
OK. Thanks. I'll start reviewing this as soon as possible.

2021-07-29 11:22 UTC, smoelius commented on dylint/src/driver_builder.rs
> +        let home = dirs::home_dir().ok_or_else(|| anyhow!("Could not find the HOME Directory."))?;
```suggestion
        let home = dirs::home_dir().ok_or_else(|| anyhow!("Could not find HOME directory"))?;
```
Nit to be consistent with error messages elsewhere.

2021-07-29 11:27 UTC, smoelius commented on dylint/src/driver_builder.rs
> +    // To succesfully determine the dylint driver Version on Windows,
```suggestion
    // MinerSebas: To succesfully determine the dylint driver Version on Windows,
```
I find it helpful to know who left comments. (I have yet to add a CONTRIBUTING.md file.)

2021-07-29 11:29 UTC, smoelius commented on internal/src/env.rs
> +pub const HOME: &str = "HOME"; // Todo: Remove this on the next major semver change.
```suggestion
```
This package is meant to be internal to Dylint. So I have no problem removing this line now.

2021-07-29 11:41 UTC, smoelius commented on dylint/src/driver_builder.rs
> +            .join(env::var(env::RUSTUP_HOME)?)
```suggestion
        let rustup_home = var(env::RUSTUP_HOME)?;
        let path = PathBuf::from(rustup_home)
```
When an environment variable cannot be found,`dylint_internal::env::var` tells you which one.

2021-07-29 11:44 UTC, smoelius commented on dylint/src/driver_builder.rs
> +                if file_name.ends_with(".dll") {
```suggestion
                if file_name.ends_with(consts:: EXE_SUFFIX) {
```
I think a `use` declaration will need to be added.

2021-07-29 11:54 UTC, smoelius requested changes
All my suggestions are minor. I really appreciate you doing this!

I have requested the help of someone with more Windows experience than me (@woodruffw) to also take a look.

2021-07-29 14:10 UTC, woodruffw commented
Took a brief look, no major objections to the code itself!

One thing to consider: it's possible to load the correct DLLs without having to copy them, by doing something tricky like this:

1. `cargo-dylint` is run by the user
2. `cargo-dylint` detects that it's on Windows
3. `cargo-dylint` re-spawns itself *in the toolchain directory*, with a special flag or environment variable telling it to change back to the package directory ASAP

This is consistent with Windows' convoluted DLL-load rules (since the re-spawned `cargo-dylint` would have have the correct `$CWD` for relative DLL discovery) and avoids a bunch of file copies. OTOH, it's a little bit harder to follow in terms of control flow and the driver already does a bunch of copying, so maybe it's not worth it. Just thought I'd put it out there!

2021-07-29 14:35 UTC, smoelius commented
Thanks a lot, @woodruffw.

Re re-spawning in the toolchain directory: I too think I am okay with the copying for now. We'll want to keep this idea in mind though. Thanks a lot for the suggestion.

@MinerSebas, if you could just review my suggestions, I think we should be good to go.

2021-07-29 21:09 UTC, smoelius commented
Thanks again, @MinerSebas.

2021-07-29 21:09 UTC, merged