Added `--pipe-stderr` and `--pipe-stdout` flags
trailofbits/dylint pull request #822
Opened 2023-09-04 15:33 UTC by faculerena

We are using dylint in our project [Scout](https://github.com/coinfabrik/scout) and added the flags `--pipe-stderr` and `--pipe-stdout` in order to manually capture the output, allowing for later processing, both from the CLI and when using the Dylint crate. We'd appreciate if you accept the change. Great work on Dylint!.

2023-09-04 15:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/trailofbits/dylint?pullRequest=822) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/trailofbits/dylint?pullRequest=822) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/trailofbits/dylint?pullRequest=822) it.</sub>

2023-09-05 18:45 UTC, smoelius requested changes
Sorry for the number of requested changes. Hopefully, they all make sense.

I will be happy to merge once these minor points are addressed.

2023-09-05 18:45 UTC, smoelius commented on cargo-dylint/src/main.rs
> +    pipe_stdout: Option<String>,
Could we please move `pipe_stderr` and `pipe_stdout` up so that they appear between `packages` and `quiet`?

2023-09-05 18:45 UTC, smoelius commented on cargo-dylint/src/main.rs
> +            pipe_stdout,
Could we reorder here to be consistent with the above change?

2023-09-05 18:45 UTC, smoelius commented on cargo-dylint/src/main.rs
> +            pipe_stdout,
Reorder here too, please.

2023-09-05 18:45 UTC, smoelius commented on dylint/src/lib.rs
> +use std::fs::OpenOptions;
Nit. Please combine this with `use` statement just below it.

2023-09-05 18:45 UTC, smoelius commented on dylint/src/lib.rs
> +    pub pipe_stdout: Option<String>,
Could we please move these up so that they appear between `paths` and `quiet`?

2023-09-05 18:45 UTC, smoelius commented on dylint/src/lib.rs
> +        let mut result = command
```suggestion
        command
```

And change the `result` to `command` between here and line 554 below.

2023-09-05 18:45 UTC, smoelius commented on dylint/src/lib.rs
> +        let result = result.success();
```suggestion
        let result = command.success();
```

2023-09-05 18:45 UTC, smoelius commented on dylint/src/lib.rs
> +                .context("Failed to open file for stderr usage")?;
```suggestion
                .with_context(|| format!("Failed to open `{}` for stderr usage", stderr_path))?;
```

2023-09-05 18:45 UTC, smoelius commented on dylint/src/lib.rs
> +                .open(path)
```suggestion
                .open(&stderr_path)
```
And then remove the declaration of `path` just above. (I think this should work.)

2023-09-05 18:45 UTC, smoelius commented on dylint/src/lib.rs
> +                .open(path)
```suggestion
                .open(&stdout_path)
```

2023-09-05 18:45 UTC, smoelius commented on dylint/src/lib.rs
> +                .context("Failed to open file for stdout usage")?;
```suggestion
                .with_context(|| format!("Failed to open `{}` for stdout usage", stdout_path))?;
```

2023-09-05 18:45 UTC, smoelius commented on cargo-dylint/src/main.rs
> +    #[clap(long, value_name = "path", help = "Path to file to pipe stderr to.")]
```suggestion
    #[clap(long, value_name = "path", help = "Path to file to pipe stderr to")]
```
To be consistent with the other option descriptions.

2023-09-05 18:45 UTC, smoelius commented on cargo-dylint/src/main.rs
> +    #[clap(long, value_name = "path", help = "Path to file to pipe stdout to.")]
```suggestion
    #[clap(long, value_name = "path", help = "Path to file to pipe stdout to")]
```

2023-09-05 20:32 UTC, faculerena commented
Valid changes, done and pushed. Also, if you merge it, do you know when the next release will drop? In the meantime, we are working with the fork so no worries! 
Thanks for the review and the project!

2023-09-05 22:50 UTC, faculerena commented
The "CI/ test (windows-latest, examples) is failing but I don't think it's related to this modifications
```
  -error: multiple versions for dependency `winapi`: 0.2.8, 0.3.9
  +error: could not read cargo metadata: `cargo metadata` exited with an error: error: failed to download `winapi v0.2.8`
  +       
  +       Caused by:
  +         unable to get packages from source
  +       
  +       Caused by:
  +         failed to download replaced source registry `crates-io`
  +       
  +       Caused by:
  +         failed to unpack package `winapi v0.2.8`
  +       
  +       Caused by:
  +         failed to remove directory `C:/Users/runneradmin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winapi-0.2.8`
  +       
  +         Caused by:
  +             The process cannot access the file because it is being used by another process. (os error 32)
  +       
  +         Error: failed to remove directory `C:/Users/runneradmin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winapi-0.2.8`
  +       
  +       Caused by:
  +         The process cannot access the file because it is being used by another process. (os error 32)
     |
     = note: `-D clippy::multiple-crate-versions` implied by `-D warnings`
   
   error: could not compile `multiple_crate_versions` (bin "multiple_crate_versions") due to previous error
```

2023-09-06 01:13 UTC, smoelius commented
It looks like the failure was sporadic.

I will publish a new version before the end of the week.

Thanks very much for your contribution!

2023-09-06 03:21 UTC, merged

2023-09-07 00:18 UTC, smoelius commented
This was released in version [2.3.0](https://github.com/trailofbits/dylint/releases/tag/v2.3.0). Please let me know if it doesn't work as you expect.

2023-09-07 13:30 UTC, faculerena commented
Works perfect, thank you!